### ISSUE TITLE
Unzipped size must be smaller than 132586253 bytes

### ISSUE THREAD

**Issue by mebibou** [developmentseed/geolambda#80]
When using the layer
```
arn:aws:lambda:us-east-1:552188055668:layer:geolambda-python:3
```
I cannot deploy to Lambda because I will get this error:
```
An error occurred: MyLambdaFunction - Unzipped size must be smaller than 132586253 bytes (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: c9e35258-e012-4ca1-a70f-05037bb70aef).
```
How can I use the layer on python 3 without having a limit problem?

**Comment by vincentsarago** [comment]
Hi @mebibou, This error means that your own package is too big (when unzipped). From my understanding, the geolambda layer must weight around 120Mb (unzipped) so you need to make sure your package weight less than 130Mb (unzipped) (130Mb + 120Mb == 250Mb which is the limit)

**Comment by mebibou** [comment]
Ok that makes sense, I guess its because I am using some libraries that import `numpy` on their own as well and not sure how to make sure I don't double import it. That aside, I managed to go around the limitation by using `zip: true` in the `serverless.yml` (which zipped the dependencies), but now I am getting this error when running the function:
```
[Errno 2] No such file or directory: '/usr/bin/ogr2ogr': '/usr/bin/ogr2ogr'
```
I did set `GDAL_DATA: /opt/share/gdal` in my env though.

My full `serverless.yml`:
```yaml
service: helloworld

provider:
  name: aws
  runtime: python3.7

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
    zip: true

package:
  exclude:
    - '**/*'
  include:
    - '*.py'

functions:
  hello:
    handler: handler.handle
    events:
      - http:
          path: /
          method: post
    layers:
      - arn:aws:lambda:us-east-1:552188055668:layer:geolambda-python:3
    environment:
      GDAL_DATA: /opt/share/gdal
      PROJ_LIB: /opt/share/proj
```
